create table ecommerce.products (
    Id serial primary key,
    Name text not null,
    Description text,
    Price numeric(10, 2) not null,
    InsertedOn timestamp default now(),
    ModifiedOn timestamp default now()
);

insert into ecommerce.products (Name, Description, Price, InsertedOn, ModifiedOn)
values
    ('Smartphone X1', 'A high-end smartphone with 128GB storage and 5G support.', 799.99, now(), now()),
    ('Smartphone X2', 'A mid-range smartphone with 64GB storage and 4G support.', 499.99, now(), now()),
    ('Laptop Pro 15', 'A powerful laptop with 16GB RAM and 512GB SSD.', 1299.99, now(), now()),
    ('Laptop Air 13', 'A lightweight laptop with 8GB RAM and 256GB SSD.', 999.99, now(), now()),
    ('Wireless Earbuds', 'Noise-cancelling wireless earbuds with 24-hour battery life.', 149.99, now(), now()),
    ('Gaming Console Z', 'Next-gen gaming console with 4K support and 1TB storage.', 499.99, now(), now()),
    ('4K Smart TV 55"', '55-inch 4K UHD Smart TV with HDR support.', 699.99, now(), now()),
    ('Bluetooth Speaker', 'Portable Bluetooth speaker with 12-hour battery life.', 99.99, now(), now()),
    ('Smartwatch Series 5', 'Smartwatch with fitness tracking and heart rate monitor.', 299.99, now(), now()),
    ('Tablet Pro 11', '11-inch tablet with 128GB storage and stylus support.', 599.99, now(), now()),
    ('Wireless Keyboard', 'Compact wireless keyboard with backlit keys.', 49.99, now(), now()),
    ('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI.', 29.99, now(), now()),
    ('External SSD 1TB', 'Portable 1TB SSD with USB-C support.', 149.99, now(), now()),
    ('Gaming Headset', 'Over-ear gaming headset with surround sound.', 89.99, now(), now()),
    ('Drone Pro', 'High-performance drone with 4K camera and GPS.', 999.99, now(), now()),
    ('Action Camera', 'Waterproof action camera with 4K recording.', 199.99, now(), now()),
    ('Smart Home Hub', 'Smart home hub with voice assistant integration.', 129.99, now(), now()),
    ('Robot Vacuum', 'Smart robot vacuum with app control and scheduling.', 399.99, now(), now()),
    ('Fitness Tracker', 'Fitness tracker with step counting and sleep monitoring.', 79.99, now(), now()),
    ('E-Reader', 'E-Reader with 8GB storage and glare-free display.', 129.99, now(), now()),
    ('Noise-Cancelling Headphones', 'Over-ear headphones with active noise cancellation.', 249.99, now(), now()),
    ('Smart Light Bulb', 'Wi-Fi enabled smart light bulb with color changing.', 19.99, now(), now()),
    ('Portable Power Bank', '10,000mAh portable power bank with fast charging.', 39.99, now(), now()),
    ('Streaming Stick', '4K streaming stick with voice remote.', 49.99, now(), now()),
    ('Smart Doorbell', 'Video doorbell with motion detection and app alerts.', 199.99, now(), now()),
    ('Electric Scooter', 'Foldable electric scooter with 15-mile range.', 499.99, now(), now()),
    ('Digital Picture Frame', '10-inch digital picture frame with Wi-Fi.', 129.99, now(), now()),
    ('Smart Thermostat', 'Smart thermostat with energy-saving features.', 249.99, now(), now()),
    ('Security Camera', 'Outdoor security camera with night vision.', 99.99, now(), now()),
    ('Gaming Monitor 27"', '27-inch gaming monitor with 144Hz refresh rate.', 299.99, now(), now()),
    ('USB-C Hub', '7-in-1 USB-C hub with HDMI and SD card reader.', 59.99, now(), now()),
    ('Wireless Charger', 'Fast wireless charger for smartphones.', 29.99, now(), now()),
    ('Smart Plug', 'Wi-Fi smart plug with app control.', 14.99, now(), now()),
    ('Electric Toothbrush', 'Rechargeable electric toothbrush with multiple modes.', 79.99, now(), now()),
    ('VR Headset', 'Virtual reality headset with motion controllers.', 399.99, now(), now()),
    ('Smart Scale', 'Smart scale with body composition analysis.', 49.99, now(), now()),
    ('Portable Projector', 'Mini projector with 1080p support.', 299.99, now(), now()),
    ('Dash Cam', 'Car dash cam with loop recording and night vision.', 99.99, now(), now()),
    ('Smart Lock', 'Keyless smart lock with app and fingerprint access.', 199.99, now(), now()),
    ('Electric Kettle', 'Smart electric kettle with temperature control.', 79.99, now(), now()),
    ('Air Purifier', 'HEPA air purifier with quiet operation.', 149.99, now(), now()),
    ('Smart Coffee Maker', 'Wi-Fi enabled coffee maker with app control.', 199.99, now(), now()),
    ('Portable Air Conditioner', 'Compact portable air conditioner with remote.', 399.99, now(), now()),
    ('Smart Oven', 'Countertop smart oven with app recipes.', 499.99, now(), now()),
    ('3D Printer', 'Desktop 3D printer with high precision.', 799.99, now(), now()),
    ('Electric Bike', 'Electric bike with 20-mile range and pedal assist.', 999.99, now(), now()),
    ('Smart Mirror', 'Smart mirror with fitness tracking and display.', 999.99, now(), now()),
    ('Smart Glasses', 'Augmented reality smart glasses with camera.', 499.99, now(), now()),
    ('Portable Speaker', 'Waterproof portable speaker with Bluetooth.', 79.99, now(), now()),
    ('Smart Refrigerator', 'Wi-Fi enabled refrigerator with touchscreen.', 1999.99, now(), now()),
    ('Smart Washer', 'Smart washing machine with app control.', 999.99, now(), now()),
    ('Smart Dryer', 'Smart dryer with energy-saving features.', 899.99, now(), now()),
    ('Smart Ceiling Fan', 'Wi-Fi enabled ceiling fan with remote.', 299.99, now(), now()),
    ('Smart Blinds', 'Motorized smart blinds with app control.', 399.99, now(), now()),
    ('Smart Water Bottle', 'Smart water bottle with hydration tracking.', 49.99, now(), now()),
    ('Smart Backpack', 'Backpack with built-in charging and anti-theft features.', 149.99, now(), now()),
    ('Smart Bike Helmet', 'Helmet with built-in lights and turn signals.', 199.99, now(), now()),
    ('Smart Pet Feeder', 'Automatic pet feeder with app scheduling.', 129.99, now(), now()),
    ('Smart Baby Monitor', 'Wi-Fi baby monitor with HD video and audio.', 199.99, now(), now()),
    ('Smart Air Conditioner', 'Wi-Fi enabled air conditioner with app control.', 599.99, now(), now()),
    ('Smart Water Leak Detector', 'Wi-Fi water leak detector with alerts.', 49.99, now(), now()),
    ('Smart Smoke Detector', 'Smart smoke detector with app notifications.', 99.99, now(), now()),
    ('Smart Garage Door Opener', 'Wi-Fi enabled garage door opener with app control.', 199.99, now(), now()),
    ('Smart Sprinkler', 'Smart sprinkler system with weather-based scheduling.', 299.99, now(), now()),
    ('Smart Bed', 'Adjustable smart bed with sleep tracking.', 1999.99, now(), now()),
    ('Smart Treadmill', 'Treadmill with app workouts and tracking.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now()),
    ('Smart Elliptical', 'Elliptical machine with app workouts.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now()),
    ('Smart Elliptical', 'Elliptical machine with app workouts.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now()),
    ('Smart Elliptical', 'Elliptical machine with app workouts.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now()),
    ('Smart Elliptical', 'Elliptical machine with app workouts.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now()),
    ('Smart Elliptical', 'Elliptical machine with app workouts.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now()),
    ('Smart Elliptical', 'Elliptical machine with app workouts.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now()),
    ('Smart Elliptical', 'Elliptical machine with app workouts.', 1499.99, now(), now()),
    ('Smart Rowing Machine', 'Rowing machine with app integration.', 999.99, now(), now()),
    ('Smart Bike Trainer', 'Indoor bike trainer with app workouts.', 799.99, now(), now()),
    ('Smart Yoga Mat', 'Yoga mat with posture tracking and app guidance.', 199.99, now(), now()),
    ('Smart Jump Rope', 'Jump rope with fitness tracking and app.', 49.99, now(), now()),
    ('Smart Dumbbells', 'Adjustable dumbbells with app tracking.', 399.99, now(), now()),
    ('Smart Mirror Gym', 'Full-length smart mirror with fitness classes.', 1999.99, now(), now());
